--- 
user: casserolesdeploy
group: casserolesdeploy
log_file: log/mongrel.log
port: "16000"
environment: production
address: 127.0.0.1
pid_file: log/mongrel.pid
servers: 4
cwd: "/u/apps/casseroles/current"
